---
title: "Assignment_1-3"
output: 
  html_document: 
    theme: sandstone
date: "2023-03-20"
---

<br/>
Assignment_1-3 작성자 : 20192237 윤우석
<br/>

```{r message=FALSE}
# 사용할 패키지 추가
library(ggplot2)
library(tidyr)
library(dplyr)
library(ggthemes)
library(ggmap)
```

<br/>
1. 숭실대입구(살피재) 역의 11월 1일의 시간대별 승차 및 하차 인원 수를 하나의 그래프로 시각화해보자.
<br/>

```{r graph1}
# 데이터 파일 읽기
metro <- read.csv("metro.csv", fileEncoding = "euc-kr")
str(metro)

#  char 형태인 날짜 컬럼을 Date 형식으로 변환
metro$날짜<- as.Date(as.character(metro$날짜))
str(metro)

# 숭실대입구역에서 11월 1일에 승/하차 데이터 추출
Nov1st_metro<- subset(metro, 날짜 == "2019-11-01" & 역명 == "숭실대입구(살피재)" )
str(Nov1st_metro)

# 시간대를 칼럼으로 가지는 데이터프레임 생성
Nov1st_metro <- gather(Nov1st_metro, key="시간대", value="인원분포", X04...05:X03...04)
str(Nov1st_metro)

# 문자형인 시간대 칼럼을 범주형으로 바꿔주고 다시 연속형 변수인 시간의 값을 갖게 하기 위해 numeric으로 변환
Nov1st_metro$시간대 <- as.numeric(factor(Nov1st_metro$시간대, levels=c("X00...01", "X01...02", "X02...03", "X03...04", "X04...05", "X05...06", "X06...07", "X07...08","X08...09","X09...10","X10...11", "X11...12", "X12...13", "X13...14", "X14...15", "X15...16", "X16...17", "X17...18", "X18...19", "X19...20", "X20...21", "X21...22", "X22...23" , "X23...24")))
str(Nov1st_metro)

# 구분(승차/하차)를 기준으로 두가지의 line plot 그리기
p <- ggplot(Nov1st_metro, aes(x=시간대, y=인원분포, group=구분, color = 구분)) + geom_line() + geom_point() + labs(title = "11월 1일 시간별 승하차 인원분포", subtitle = "역명 : 숭실대입구역") + scale_x_continuous(breaks = seq(1,24,1), labels = c("0~1", "1~2", "2~3", "3~4", "4~5", "5~6", "6~7", "7~8", "8~9", "9~10", "10~11", "11~12", "12~13", "13~14", "14~15", "15~16", "16~17", "17~18", "18~19", "19~20", "20~21", "21~22", "22~23", "23~24")) + scale_y_continuous(breaks = seq(0, 3000, 500))  + theme(axis.text.x = element_text(angle = 45, hjust = 1))
p

```

<br/>
2. 숭실대입구(살피재) 역의 11월 10일(일)부터 11월16일(토)까지 일주일간 각 요일별 시간대별 승차인원과 하차인원의 분포를 각각 heat map으로 시각화해보자.
<br/>

```{r graph2}

# metro 데이터에서 숭실대입구역의 2019-11-10일부터 2019-11-16일까지 승/하차 데이터 추출"
week3_metro <- subset(metro, 날짜 >= "2019-11-10" & 날짜 <= "2019-11-16" & 역명 == "숭실대입구(살피재)" )
str(week3_metro)

# 시간대를 칼럼으로 가지는 데이터프레임 생성
week3_metro <- gather(week3_metro, key="시간대", value="인원수", X04...05:X03...04)
str(week3_metro)

# 시간대 컬럼의 유형을 factor로 변환
week3_metro$시간대 <- factor(week3_metro$시간대, levels=c("X00...01", "X01...02", "X02...03", "X03...04", "X04...05", "X05...06", "X06...07", "X07...08", "X08...09", "X09...10", "X10...11", "X11...12", "X12...13", "X13...14", "X14...15", "X15...16", "X16...17", "X17...18", "X18...19", "X19...20", "X20...21", "X21...22", "X22...23" , "X23...24"), labels=c("0시 ~ 1시", "1시 ~ 2시", "2시 ~ 3시", "3시 ~ 4시", "4시 ~ 5시", "5시 ~ 6시", "6시 ~ 7시", "7시 ~ 8시", "8시 ~ 9시", "9시 ~ 10시", "10시 ~ 11시", "11시 ~ 12시", "12시 ~ 13시", "13시 ~ 14시", "14시 ~ 15시", "15시 ~ 16시", "16시 ~ 17시", "17시 ~ 18시", "18시 ~ 19시", "19시 ~ 20시", "20시 ~ 21시", "21시 ~ 22시", "22시 ~ 23시", "23시 ~ 24시"))
str(week3_metro)

# 날짜 컬럼의 유형을 factor로 변환
week3_metro$날짜 <- factor(week3_metro$날짜, levels=c("2019-11-10", "2019-11-11", "2019-11-12", "2019-11-13", "2019-11-14", "2019-11-15", "2019-11-16"), labels = c("일요일", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일"))
str(week3_metro)


# 승하차 Heatmap 그리기
p1 <- ggplot(data = week3_metro, aes(x = 날짜, y = 시간대, fill = 인원수)) + geom_tile() + labs(title = "11월 3째주 요일별 시간별 승하차인원분포", subtitle = "역명 : 숭실대입구역, 기간 : 2019-11-10 ~ 2019-11-16") + facet_wrap(~구분) + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_fill_gradient(low = "yellow", high = "red")
p1

# 시간대 컬럼을 숫자형으로 변환하기
week3_metro$시간대 <- as.numeric(week3_metro$시간대)
str(week3_metro)

# 시간대 컬럼을 숫자형으로 변환한 승하차 Heatmap 그리기기
p2 <-ggplot(data = week3_metro, aes(x = 날짜, y = 시간대, fill = 인원수)) + geom_tile() + labs(title = "11월 3째주 요일별 시간별 승하차인원분포", subtitle = "역명 : 숭실대입구역, 기간 : 2019-11-10 ~ 2019-11-16") + facet_wrap(~구분) + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_fill_gradient(low = "yellow", high = "red")
p2

```


<br/>
3. 7호선의 모든 역 중에서 유동인구(월간 승하차 전체인원)가 가장 많은 15개 역에 대한 유동인구 수를 그래프로 시각화해보자.
<br/>

```{r graph3}

#metro 데이터의 시간대별 데이터의 총합 컬럼을 생성
metro$total <- rowSums(metro[,7:30])
str(metro)

# 7호선 데이터만 추출
metro_station <- subset(metro, 호선 == "7호선")
str(metro_station)

# 승/하차가 나누어 졌을 때 역명을 기준으로 sum
metro_station <- aggregate(x=metro_station[-1:-30], by=list(metro_station$역명), sum)
str(metro_station)

# total 값으로 내림차순으로 정렬
metro_Station_ordered <- arrange(metro_station, -total)
str(metro_Station_ordered)

# 내림차순시 상위 15개의 값을 표시
metro_Station_15 <- metro_Station_ordered[1:15,]
str(metro_Station_15)

# 7호선의 모든 역 중에서 유동인구(월간 승하차 전체인원)가 가장 많은 15개 역에 대한 유동인구 수를 그래프 그리기
p <- ggplot(metro_Station_15, aes(x=reorder(Group.1, total), y=total)) + geom_bar(stat="identity", fill = "cornflowerblue") + coord_flip() + scale_y_continuous(breaks = seq(0, 3000000, 500000), name = "월간 승하차 전체인원", labels =c(0, "50만", "100만", "150만", "200만", "250만", "300만")) + xlab("역명") + labs(title = "7호선 유동인구 TOP 15 지하철역", subtitle = "2019-11-01 ~ 2019-11-31") +  geom_text(aes(label = total), size = 2)
p

```

<br/>
4. 7호선 지하철역 위치 정보를 활용하여 7호선의 모든 역에 대한 유동인구 분포를 지도 위에 시각화해보자.크기, 투명도 등을 활용하여 분포를 표현할 수 있다.
<br/>

```{r graph4}
# 7호선 지하철 역 위치 파일 읽기
metro_coord <- read.csv("metro_coord.csv", fileEncoding = "euc-kr")
str(metro_coord)

# 보여지는 지도 위도, 경도 설정
bbox_seoul <- c(left = 126.65, bottom = 37.458073, right = 127.194848, top = 37.72)

# 서울을 보여주는 지도 생성
seoul <- get_stamenmap(bbox = bbox_seoul, zoom = 11, maptype =  "terrain")

# join을 위한 컬럼명 변경
names(metro_station)[1] <- c("역명")

# 데이터셋 join
metro_coord <- left_join(metro_coord, metro_station, by="역명")
str(metro_coord)

# 7호선 모든 역에 대한 유동인구 분포 시각화, 유동인구는 점의 크기로 표현
Station7 <- ggmap(seoul, base_layer = ggplot(data = metro_coord, aes(x=lon, y=lat, size = total))) + geom_point(color = "red", alpha = 0.5) + scale_size_continuous(name="유동인구", breaks = c(500000, 1000000, 1500000, 2000000), labels = c("50만", "100만", "150만", "200만")) + geom_text(aes(label = 역명), size = 2) +
labs(title = "<7호선 지하철역 지도 및 유동인구>")
Station7

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
